apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow-istio-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kubeflow/manifests.git
    targetRevision: v1.11.0
    path: common/istio/kubeflow-istio-resources/base
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
