apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow-kserve
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/kubeflow/manifests.git
      targetRevision: v1.11.0
      path: applications/kserve/kserve
    - repoURL: https://github.com/kubeflow/manifests.git
      targetRevision: v1.11.0
      path: applications/kserve/models-web-app/overlays/kubeflow
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
